language: node_js
node_js: '8'
install:
- npm install
script:
- npm test
deploy:
- provider: npm
  api_key: "${AUTH_TOKEN}"
  email: it@olono.ai
  on:
    branch: master
env:
  global:
    secure: YOrMVZriu3U+PVt0XzwqqkDr2U1fT+s5Kwv4uXCIERDEtIJrSz3d+BVj/JZv8CQ2XmOfOs6hSX938j1G52LKo2Fmsz5Dnkm3mJhicyoZ4swrvZTNfMfj0w/FnTchzVofg+T6yUmAKukdnLrgEZ5nJG7TVyz1aMXcAQyIZtZ1cSXegsuXPz3Jtx7cD6c+INv1MCfQ5eliINPwwlBivQh4dV22KkEGvhadNzEUqS1j5PU/AgzFG9xt/y7QJ2BF/YgPE1eI9wOWce/mmK2Dw0wI7A6JhQ9JwPklipCSL6/5wIQS9ANAHRtC3RSIqmQxi65plmPTb0l5kC9e9fbnqr2UdMteRm6sjDnnAhMLMyp/JLNFVzsKyN9Yjt5XnGCD5d2s7t/IW+VQCcRIXL2VjOHE1ZhkIEhlPY42klWyhSXCxM3lrPL4Xu6uO9lVGbcFYU52DdhcwL3XLIeDbkl0B2NsKqlGqikW+UGcqtcGpTYqxqieEdR0C7LWw+yFaBr1I9bxXCbWLcGg0pUeGgp6t6okkmwKC+3wLEAG1qfUoNktxEiK8b4Ljg+RFyaMS9rNYJxUtAgCe+G33CkpmKxC4ME4WEF2NmEIYEQ/pM27nWAad22vzAfF+UEeRpmuK/wntrEGlSwkXnfPFv2rqJS4vFpXM3WOVLJjvCa7F46VZugyEQo=
