language: node_js
node_js: '8'
install:
- npm install
script:
- npm test
deploy:
- provider: npm
  api_key: "${AUTH_TOKEN}"
  email: opensource@olono.ai
  on:
    branch: master
env:
  global:
    secure: uBuB6GMrftYO4SlsXMe3OlO6reIS2vJg+XWZ27ULyeZmyo1LVKZrJlJAwjqq4smyR0jsAxmU4CE9k3KZY/E7v7qu2J9aB9dw5TpgCrcftQz3aTyGfWZk98/Wfqe9FoeD2opiVUDyZVW6vaH/41B+aIpA3j6kXhm3iBkQ8xPNhIw8AqQsCvFCOtPKBckX+FTUtTM9H+zVpzVXiKWjY3Ht98ka+0/iNaVeMzM6qr0ZOqhoOY9Y7/Sq6vM9ql3n77ppavXysZDGVlTncChs51D88R5ByLGnykJOAlHcbeKBpAKuwLI+Qa224l8yUTELSAU1w8Bc3QGk69WJbyfxE618lNPlO81AKA44YYMzGwYpcmnSZIbQy4E7BCCaYOjfGj3Vu/BvZmykMA1VjSkqP7UHTtVSwhjpRblafMaLpwS+YavJaGh5U5TC+hdti5joPIFq7zzPPgmwP/txFwrtmt/QFHZuvHa74ibsvEfrBLIko9yznmPdki1qxgo6O9JE7Ys3iqCjs/i53v4ps60OSQiwMkXbaz76D4F8e563pj4WkfzWh1qtoJktZglmsQpVX+BU3rCwIwsjO298O8CLicC3s+yj4eZsDQLv9o3oEjwRGftaqy8716Q/SF4On2wYfgabKmwR3JN3Fwbu4FEPHu5p1aG2mUdmCL2eiSObqTzkbCU=
